//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadoMagiDataCounter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Credits")]
        public string CreditsTitle {
            get {
                return ((string)(this["CreditsTitle"]));
            }
            set {
                this["CreditsTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Payouts")]
        public string PayoutsTitle {
            get {
                return ((string)(this["PayoutsTitle"]));
            }
            set {
                this["PayoutsTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Return Rate")]
        public string ReturnTitle {
            get {
                return ((string)(this["ReturnTitle"]));
            }
            set {
                this["ReturnTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Play Time")]
        public string TimerTitle {
            get {
                return ((string)(this["TimerTitle"]));
            }
            set {
                this["TimerTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("プチBONUS")]
        public string SmallBonusTitle {
            get {
                return ((string)(this["SmallBonusTitle"]));
            }
            set {
                this["SmallBonusTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("... since")]
        public string SmallTimeTitle {
            get {
                return ((string)(this["SmallTimeTitle"]));
            }
            set {
                this["SmallTimeTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BIG BONUS")]
        public string BigBonusTitle {
            get {
                return ((string)(this["BigBonusTitle"]));
            }
            set {
                this["BigBonusTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("... since")]
        public string BigTimeTitle {
            get {
                return ((string)(this["BigTimeTitle"]));
            }
            set {
                this["BigTimeTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alarm")]
        public string AlertTitle {
            get {
                return ((string)(this["AlertTitle"]));
            }
            set {
                this["AlertTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?? 1")]
        public string Unk1Title {
            get {
                return ((string)(this["Unk1Title"]));
            }
            set {
                this["Unk1Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?? 2")]
        public string Unk2Title {
            get {
                return ((string)(this["Unk2Title"]));
            }
            set {
                this["Unk2Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string LastCOM {
            get {
                return ((string)(this["LastCOM"]));
            }
            set {
                this["LastCOM"] = value;
            }
        }
    }
}
